name: postgres_pool
description: Postgresql connection pool with a wide range of automated reconnect parameters.
version: 2.1.0
homepage: https://github.com/agilord/postgres_pool

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  executor: ^2.2.2
  postgres: ^2.3.0
  retry: ^3.1.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
