name: postgres_pool
description: Postgresql connection pool with a wide range of automated reconnect parameters.
version: 2.1.6
homepage: https://github.com/agilord/postgres_pool

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  executor: ^2.0.0
  postgres: ^2.5.0
  retry: ^3.0.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.6.0
